# Generated by Django 4.2.30 on 2026-04-27 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATED_ITEM', 'Created Item'), ('UPDATED_ITEM', 'Updated Item'), ('DELETED_ITEM', 'Deleted Item'), ('VIEWED_ITEM', 'Viewed Item'), ('ARCHIVED_ITEM', 'Archived Item')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
    ]
